/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Wed Sep 25 23:48:23 GMT 2019
 */

package src.evo.com.kechen.controller;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class MyController_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.kechen.controller.MyController"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/xy/fhlysf01351_pkdrl51wsy5h0000gn/T/"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "/Users/victor/IdeaProjects/lootcode/src/main"); 
    java.lang.System.setProperty("user.home", "/Users/victor"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "victor"); 
    java.lang.System.setProperty("user.timezone", "America/New_York"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(MyController_ESTest_scaffolding.class.getClassLoader() ,
      "com.kechen.repository.NoteRepository",
      "com.kechen.domain.Note",
      "org.springframework.util.LinkedCaseInsensitiveMap",
      "org.springframework.beans.factory.annotation.Autowired",
      "com.kechen.repository.ProblemRepository",
      "org.springframework.stereotype.Controller",
      "org.springframework.http.ResponseEntity$BodyBuilder",
      "org.springframework.data.repository.CrudRepository",
      "com.kechen.service.ProblemService",
      "com.kechen.domain.Problem_Company",
      "com.kechen.controller.MyController",
      "com.kechen.domain.User",
      "org.springframework.stereotype.Service",
      "org.springframework.data.repository.Repository",
      "com.kechen.domain.ProblemCode",
      "org.springframework.stereotype.Repository",
      "com.kechen.domain.Problem",
      "com.kechen.service.UserService",
      "com.kechen.repository.CodeRepository",
      "com.kechen.domain.Company",
      "org.springframework.http.HttpHeaders",
      "org.springframework.util.MultiValueMap",
      "org.springframework.web.bind.annotation.ResponseBody",
      "org.springframework.web.bind.annotation.RestController",
      "org.springframework.util.LinkedCaseInsensitiveMap$1",
      "org.springframework.http.HttpStatus",
      "org.springframework.http.HttpEntity",
      "org.springframework.stereotype.Component",
      "com.kechen.domain.User_Problem",
      "com.kechen.repository.UserRepository",
      "org.springframework.http.ResponseEntity",
      "org.springframework.http.ResponseEntity$HeadersBuilder",
      "com.kechen.domain.Problem_Code",
      "com.kechen.repository.CompanyRepository",
      "com.kechen.domain.Code",
      "org.springframework.util.Assert"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("com.kechen.domain.Problem", false, MyController_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.kechen.repository.CodeRepository", false, MyController_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.kechen.repository.CompanyRepository", false, MyController_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.kechen.repository.NoteRepository", false, MyController_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.kechen.repository.ProblemRepository", false, MyController_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.kechen.repository.UserRepository", false, MyController_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.kechen.service.ProblemService", false, MyController_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.kechen.service.UserService", false, MyController_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(MyController_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.kechen.controller.MyController",
      "org.springframework.web.bind.annotation.RequestMethod",
      "org.springframework.web.bind.annotation.CrossOrigin",
      "org.springframework.http.HttpStatus",
      "com.kechen.service.ProblemService",
      "com.kechen.service.UserService",
      "org.springframework.http.HttpHeaders",
      "org.springframework.util.LinkedCaseInsensitiveMap",
      "org.springframework.util.LinkedCaseInsensitiveMap$1",
      "org.springframework.util.Assert",
      "org.springframework.http.HttpEntity",
      "org.springframework.http.ResponseEntity",
      "com.kechen.domain.User",
      "com.kechen.domain.Problem",
      "com.kechen.domain.User_Problem",
      "com.kechen.domain.ProblemCode",
      "com.kechen.domain.Problem_Company",
      "com.kechen.domain.Problem_Code",
      "com.mysql.jdbc.AbandonedConnectionCleanupThread",
      "com.mysql.jdbc.NonRegisteringDriver",
      "com.mysql.jdbc.Driver",
      "com.mysql.fabric.jdbc.FabricMySQLDriver",
      "com.kechen.domain.Company",
      "com.kechen.domain.Code"
    );
  }
}
