/*
 * This file was automatically generated by EvoSuite
 * Thu Sep 26 00:18:55 GMT 2019
 */

package com.kechen.IdClasses;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import com.kechen.IdClasses.PComId;
import com.kechen.domain.Company;
import com.kechen.domain.Problem;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PComId_ESTest extends PComId_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PComId pComId0 = new PComId();
      PComId pComId1 = new PComId();
      assertTrue(pComId1.equals((Object)pComId0));
      
      Company company0 = mock(Company.class, new ViolatedAssumptionAnswer());
      pComId1.setCompany(company0);
      boolean boolean0 = pComId0.equals(pComId1);
      assertFalse(pComId1.equals((Object)pComId0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PComId pComId0 = new PComId();
      Problem problem0 = mock(Problem.class, new ViolatedAssumptionAnswer());
      Company company0 = mock(Company.class, new ViolatedAssumptionAnswer());
      PComId pComId1 = new PComId(problem0, company0);
      boolean boolean0 = pComId0.equals(pComId1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PComId pComId0 = new PComId();
      PComId pComId1 = new PComId((Problem) null, (Company) null);
      boolean boolean0 = pComId0.equals(pComId1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PComId pComId0 = new PComId();
      boolean boolean0 = pComId0.equals(pComId0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      PComId pComId0 = new PComId();
      boolean boolean0 = pComId0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      PComId pComId0 = new PComId();
      pComId0.hashCode();
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      PComId pComId0 = new PComId();
      pComId0.setProblem((Problem) null);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      PComId pComId0 = new PComId();
      Problem problem0 = pComId0.getProblem();
      assertNull(problem0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      PComId pComId0 = new PComId();
      Company company0 = pComId0.getCompany();
      assertNull(company0);
  }
}
