/*
 * This file was automatically generated by EvoSuite
 * Wed Sep 25 23:50:24 GMT 2019
 */

package com.kechen.IdClasses;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import com.kechen.IdClasses.PComId;
import com.kechen.domain.Company;
import com.kechen.domain.Problem;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PComId_ESTest extends PComId_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PComId pComId0 = new PComId();
      PComId pComId1 = new PComId();
      boolean boolean0 = pComId0.equals(pComId1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Problem problem0 = mock(Problem.class, new ViolatedAssumptionAnswer());
      Company company0 = mock(Company.class, new ViolatedAssumptionAnswer());
      PComId pComId0 = new PComId(problem0, company0);
      Problem problem1 = mock(Problem.class, new ViolatedAssumptionAnswer());
      Company company1 = mock(Company.class, new ViolatedAssumptionAnswer());
      PComId pComId1 = new PComId(problem1, company1);
      boolean boolean0 = pComId0.equals(pComId1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PComId pComId0 = new PComId();
      Problem problem0 = pComId0.getProblem();
      boolean boolean0 = pComId0.equals(problem0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PComId pComId0 = new PComId();
      boolean boolean0 = pComId0.equals(pComId0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      PComId pComId0 = new PComId();
      Company company0 = mock(Company.class, new ViolatedAssumptionAnswer());
      pComId0.setCompany(company0);
      PComId pComId1 = new PComId();
      boolean boolean0 = pComId0.equals(pComId1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Problem problem0 = mock(Problem.class, new ViolatedAssumptionAnswer());
      doReturn("&K").when(problem0).toString();
      Company company0 = mock(Company.class, new ViolatedAssumptionAnswer());
      PComId pComId0 = new PComId(problem0, company0);
      Problem problem1 = pComId0.getProblem();
      pComId0.setProblem(problem1);
      assertEquals(0, problem1.getDifficulty());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Problem problem0 = mock(Problem.class, new ViolatedAssumptionAnswer());
      Company company0 = mock(Company.class, new ViolatedAssumptionAnswer());
      PComId pComId0 = new PComId(problem0, company0);
      pComId0.hashCode();
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      PComId pComId0 = new PComId();
      Company company0 = pComId0.getCompany();
      assertNull(company0);
  }
}
